#!/usr/bin/env python3
"""
Restart-aware GCMC-MD equilibrium analyzer.

It reads one or more monitor_gcmc_*.dat files generated by LAMMPS fix ave/time.

Recommended usage:
  python3 analyze_gcmc_equilibrium_restart.py monitor_gcmc_rh09.dat --window-steps 500000

If you have several segment files:
  python3 analyze_gcmc_equilibrium_restart.py monitor_seg1.dat monitor_seg2.dat monitor_seg3.dat --window-steps 500000

If timestep was reset between segments, use:
  --auto-offset-restarts

Expected columns:
  step nwater_total nwater_inter nwater_bottom nwater_top nwater_ext
  basal_proxy zcenter iacc dacc tacc racc temp pe
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np


DEFAULT_COLUMNS = [
    "step",
    "nwater_total",
    "nwater_inter",
    "nwater_bottom",
    "nwater_top",
    "nwater_ext",
    "basal_proxy",
    "zcenter",
    "iacc",
    "dacc",
    "tacc",
    "racc",
    "temp",
    "pe",
]


def parse_one_monitor(path: Path) -> Tuple[List[str], np.ndarray]:
    rows: List[List[float]] = []
    columns = DEFAULT_COLUMNS[:]

    with path.open("r", errors="ignore") as f:
        for line in f:
            s = line.strip()
            if not s:
                continue

            if s.startswith("#"):
                if "TimeStep" in s and "v_nwater_mol" in s:
                    raw = s.lstrip("#").split()
                    converted = []
                    for name in raw:
                        if name == "TimeStep":
                            converted.append("step")
                        elif name.startswith("v_"):
                            converted.append(name[2:])
                        else:
                            converted.append(name)
                    rename = {
                        "nwater_mol": "nwater_total",
                        "nwat_inter": "nwater_inter",
                        "nwat_bottom": "nwater_bottom",
                        "nwat_top": "nwater_top",
                        "nwat_ext": "nwater_ext",
                        "temp_inst": "temp",
                        "pe_inst": "pe",
                    }
                    columns = [rename.get(c, c) for c in converted]
                continue

            parts = s.split()
            try:
                vals = [float(x) for x in parts]
            except ValueError:
                continue

            if len(vals) == len(columns):
                rows.append(vals)
            elif len(vals) >= len(DEFAULT_COLUMNS):
                rows.append(vals[: len(DEFAULT_COLUMNS)])
                columns = DEFAULT_COLUMNS[:]

    if not rows:
        raise SystemExit(f"No numeric rows found in {path}")

    return columns, np.asarray(rows, dtype=float)


def read_monitors(paths: List[Path], auto_offset_restarts: bool) -> Dict[str, np.ndarray]:
    all_rows = []
    final_columns = None
    offset = 0.0
    previous_last_step = None

    for ipath, path in enumerate(paths):
        columns, arr = parse_one_monitor(path)
        if final_columns is None:
            final_columns = columns
        elif columns != final_columns:
            raise SystemExit(f"Column mismatch in {path}")

        # Remove duplicated step rows inside the same file, keeping the last occurrence.
        # This is useful when repeated segment outputs are appended.
        step_col = arr[:, columns.index("step")]
        if len(step_col) > 1:
            _, unique_last_indices = np.unique(step_col[::-1], return_index=True)
            keep = len(step_col) - 1 - unique_last_indices
            keep = np.sort(keep)
            arr = arr[keep]
            step_col = arr[:, columns.index("step")]

        if auto_offset_restarts:
            if previous_last_step is not None and step_col[0] <= previous_last_step:
                # Assume this is a new segment after reset_timestep or overwritten monitor.
                # Add an offset so the first step follows the previous segment.
                segment_dt = np.median(np.diff(step_col)) if len(step_col) > 1 else 1000.0
                offset = previous_last_step + segment_dt - step_col[0]
            arr = arr.copy()
            arr[:, columns.index("step")] = step_col + offset
            step_col = arr[:, columns.index("step")]

        previous_last_step = float(step_col[-1])
        all_rows.append(arr)

    merged = np.vstack(all_rows)
    step_idx = final_columns.index("step")

    # Sort by step and remove duplicated steps after merging, keeping the last row.
    order = np.argsort(merged[:, step_idx])
    merged = merged[order]
    steps = merged[:, step_idx]
    _, unique_last_indices = np.unique(steps[::-1], return_index=True)
    keep = len(steps) - 1 - unique_last_indices
    keep = np.sort(keep)
    merged = merged[keep]

    # If steps are still non-monotonic, fail explicitly.
    steps = merged[:, step_idx]
    if np.any(np.diff(steps) < 0):
        raise SystemExit(
            "Non-monotonic timesteps remain. Use --auto-offset-restarts, or provide files in chronological order."
        )

    return {final_columns[i]: merged[:, i] for i in range(merged.shape[1])}


def linear_slope_per_100k(step: np.ndarray, y: np.ndarray) -> float:
    if len(step) < 2 or np.allclose(step, step[0]):
        return float("nan")
    x = step - step[0]
    slope_per_step = np.polyfit(x, y, 1)[0]
    return float(slope_per_step * 100000.0)


def coeff_var(y: np.ndarray) -> float:
    mean = float(np.mean(y))
    std = float(np.std(y, ddof=1)) if len(y) > 1 else 0.0
    if abs(mean) < 1e-12:
        return 0.0 if std < 1e-12 else float("inf")
    return abs(std / mean)


def window_slice(step: np.ndarray, window_steps: float | None, last_fraction: float) -> np.ndarray:
    if window_steps is not None and window_steps > 0:
        start = step[-1] - window_steps
        mask = step >= start
    else:
        n = max(3, int(math.ceil(len(step) * last_fraction)))
        mask = np.zeros_like(step, dtype=bool)
        mask[-n:] = True
    return mask


def bounded_window_slice(step: np.ndarray, start: float, end: float) -> np.ndarray:
    return (step >= start) & (step <= end)


def summarize_series(data: Dict[str, np.ndarray], key: str, mask: np.ndarray) -> Dict[str, float]:
    step = data["step"][mask]
    y = data[key][mask]
    return {
        "start": float(y[0]),
        "end": float(y[-1]),
        "mean": float(np.mean(y)),
        "std": float(np.std(y, ddof=1)) if len(y) > 1 else 0.0,
        "cv": coeff_var(y),
        "slope_per_100k": linear_slope_per_100k(step, y),
    }


def equilibrium_settings_from_config(
    config: Dict[str, Any],
    *,
    cli_window_steps: float | None = None,
    rh_handoff: bool = True,
) -> Dict[str, Any]:
    policy = config.get("simulation_policy", {}) if isinstance(config.get("simulation_policy"), dict) else {}
    equilibrium = config.get("equilibrium", {}) if isinstance(config.get("equilibrium"), dict) else {}
    if cli_window_steps is not None:
        configured_window = float(cli_window_steps)
    else:
        configured_window = float(policy.get("equilibrium_window_steps", equilibrium.get("window_steps", 500000)))
    if rh_handoff:
        window_steps = max(configured_window, float(equilibrium.get("rh_handoff_window_steps", 1000000)))
        require_previous = bool(equilibrium.get("require_previous_window_slopes", True))
    else:
        window_steps = configured_window
        require_previous = bool(equilibrium.get("require_previous_window_slopes", False))
    return {
        "window_steps": window_steps,
        "last_fraction": float(equilibrium.get("last_fraction", 0.3)),
        "min_points": int(equilibrium.get("min_points", 50)),
        "total_cv_max": float(equilibrium.get("total_cv_max", 0.03)),
        "inter_cv_max": float(equilibrium.get("inter_cv_max", 0.05)),
        "ext_cv_max": float(equilibrium.get("ext_cv_max", 0.08)),
        "total_slope_frac_per_100k": float(equilibrium.get("total_slope_frac", 0.01)),
        "inter_slope_frac_per_100k": float(equilibrium.get("inter_slope_frac", 0.02)),
        "ext_slope_frac_per_100k": float(equilibrium.get("ext_slope_frac", 0.02)),
        "min_water_slope_abs": float(equilibrium.get("min_water_slope_abs", 1.0)),
        "basal_slope_abs_per_100k": float(equilibrium.get("basal_slope_max_A_per_100k", 0.05)),
        "sum_tol": float(equilibrium.get("sum_tolerance", 0.5)),
        "require_previous_window_slopes": require_previous,
    }


def analyze(
    data: Dict[str, np.ndarray],
    window_steps: float | None,
    last_fraction: float,
    min_points: int,
    total_cv_max: float,
    inter_cv_max: float,
    ext_cv_max: float,
    total_slope_frac_per_100k: float,
    inter_slope_frac_per_100k: float,
    ext_slope_frac_per_100k: float,
    min_water_slope_abs: float,
    basal_slope_abs_per_100k: float,
    sum_tol: float,
    require_previous_window_slopes: bool = False,
) -> Dict:
    step = data["step"]
    mask = window_slice(step, window_steps, last_fraction)
    npts = int(np.sum(mask))

    result = {
        "status": "unknown",
        "recommendation": "unknown",
        "n_points_total": int(len(step)),
        "n_points_window": npts,
        "step_start": int(step[0]),
        "step_end": int(step[-1]),
        "window_step_start": int(step[mask][0]),
        "window_step_end": int(step[mask][-1]),
        "window_steps_requested": window_steps,
        "checks": {},
        "series": {},
        "previous_window": None,
        "reasons": [],
    }

    if npts < min_points:
        result["status"] = "not_enough_data"
        result["recommendation"] = "continue_current_rh"
        result["reasons"].append(f"Only {npts} points in final window; need at least {min_points}.")
        return result

    keys = [
        "nwater_total",
        "nwater_inter",
        "nwater_bottom",
        "nwater_top",
        "nwater_ext",
        "basal_proxy",
        "zcenter",
        "iacc",
        "dacc",
        "temp",
        "pe",
    ]
    for key in keys:
        if key in data:
            result["series"][key] = summarize_series(data, key, mask)

    total = data["nwater_total"][mask]
    parts = data["nwater_inter"][mask] + data["nwater_bottom"][mask] + data["nwater_top"][mask]
    max_sum_error = float(np.max(np.abs(total - parts)))
    result["checks"]["water_sum_consistent"] = max_sum_error <= sum_tol
    result["max_water_sum_error"] = max_sum_error
    if max_sum_error > sum_tol:
        result["reasons"].append(
            f"Water count inconsistent: max |total-(inter+bottom+top)| = {max_sum_error:.3g}."
        )

    total_cv = result["series"]["nwater_total"]["cv"]
    inter_cv = result["series"]["nwater_inter"]["cv"]
    ext_cv = result["series"]["nwater_ext"]["cv"]
    result["checks"]["total_water_cv_ok"] = total_cv <= total_cv_max
    result["checks"]["inter_water_cv_ok"] = inter_cv <= inter_cv_max
    result["checks"]["external_water_cv_ok"] = ext_cv <= ext_cv_max

    if total_cv > total_cv_max:
        result["reasons"].append(f"Total water CV too high: {total_cv:.4f} > {total_cv_max}.")
    if inter_cv > inter_cv_max:
        result["reasons"].append(f"Interlayer water CV too high: {inter_cv:.4f} > {inter_cv_max}.")
    if ext_cv > ext_cv_max:
        result["reasons"].append(f"External water CV too high: {ext_cv:.4f} > {ext_cv_max}.")

    def slope_ok(key: str, frac: float) -> bool:
        s = abs(result["series"][key]["slope_per_100k"])
        mean = abs(result["series"][key]["mean"])
        limit = max(min_water_slope_abs, frac * mean)
        result["series"][key]["slope_limit_per_100k"] = float(limit)
        ok = s <= limit
        if not ok:
            result["reasons"].append(
                f"{key} still drifting: slope={s:.3g}/100k, limit={limit:.3g}/100k."
            )
        return ok

    result["checks"]["total_water_slope_ok"] = slope_ok("nwater_total", total_slope_frac_per_100k)
    result["checks"]["inter_water_slope_ok"] = slope_ok("nwater_inter", inter_slope_frac_per_100k)
    result["checks"]["external_water_slope_ok"] = slope_ok("nwater_ext", ext_slope_frac_per_100k)

    result["checks"]["previous_window_water_slopes_ok"] = True
    if require_previous_window_slopes and window_steps is not None and window_steps > 0:
        previous_start = float(step[mask][0] - window_steps)
        previous_end = float(step[mask][0])
        previous_mask = bounded_window_slice(step, previous_start, previous_end)
        previous_npts = int(np.sum(previous_mask))
        previous: dict[str, Any] = {
            "n_points_window": previous_npts,
            "window_step_start": int(step[previous_mask][0]) if previous_npts else None,
            "window_step_end": int(step[previous_mask][-1]) if previous_npts else None,
            "series": {},
            "checks": {},
        }
        if previous_npts >= min_points:
            previous_ok = True
            for key, frac, check_name in [
                ("nwater_total", total_slope_frac_per_100k, "previous_total_water_slope_ok"),
                ("nwater_inter", inter_slope_frac_per_100k, "previous_inter_water_slope_ok"),
                ("nwater_ext", ext_slope_frac_per_100k, "previous_external_water_slope_ok"),
            ]:
                previous["series"][key] = summarize_series(data, key, previous_mask)
                s_abs = abs(previous["series"][key]["slope_per_100k"])
                mean = abs(previous["series"][key]["mean"])
                limit = max(min_water_slope_abs, frac * mean)
                previous["series"][key]["slope_limit_per_100k"] = float(limit)
                ok = s_abs <= limit
                previous["checks"][check_name] = ok
                result["checks"][check_name] = ok
                previous_ok = previous_ok and ok
                if not ok:
                    result["reasons"].append(
                        f"Previous adjacent window {key} drifted: slope={s_abs:.3g}/100k, "
                        f"limit={limit:.3g}/100k."
                    )
            result["checks"]["previous_window_water_slopes_ok"] = previous_ok
        else:
            previous["reason"] = f"Only {previous_npts} points in previous adjacent window; need at least {min_points}."
            result["checks"]["previous_window_water_slopes_ok"] = False
            result["reasons"].append(previous["reason"])
        result["previous_window"] = previous

    basal_slope = abs(result["series"]["basal_proxy"]["slope_per_100k"])
    result["checks"]["basal_slope_ok"] = basal_slope <= basal_slope_abs_per_100k
    result["series"]["basal_proxy"]["slope_limit_A_per_100k"] = basal_slope_abs_per_100k
    if basal_slope > basal_slope_abs_per_100k:
        result["reasons"].append(
            f"Basal spacing still drifting: slope={basal_slope:.4g} Å/100k, "
            f"limit={basal_slope_abs_per_100k} Å/100k."
        )

    if "temp" in result["series"]:
        t_mean = result["series"]["temp"]["mean"]
        t_min = float(np.min(data["temp"][mask]))
        t_max = float(np.max(data["temp"][mask]))
        result["series"]["temp"]["min"] = t_min
        result["series"]["temp"]["max"] = t_max
        temp_ok = (200.0 <= t_min) and (t_max <= 450.0) and (250.0 <= t_mean <= 350.0)
        result["checks"]["temperature_sanity_ok"] = temp_ok
        if not temp_ok:
            result["reasons"].append(
                f"Temperature abnormal in window: mean={t_mean:.2f}, min={t_min:.2f}, max={t_max:.2f} K."
            )

    required = [
        result["checks"].get("water_sum_consistent", False),
        result["checks"].get("total_water_cv_ok", False),
        result["checks"].get("inter_water_cv_ok", False),
        result["checks"].get("external_water_cv_ok", False),
        result["checks"].get("total_water_slope_ok", False),
        result["checks"].get("inter_water_slope_ok", False),
        result["checks"].get("external_water_slope_ok", False),
        result["checks"].get("previous_window_water_slopes_ok", True),
        result["checks"].get("basal_slope_ok", False),
        result["checks"].get("temperature_sanity_ok", True),
    ]

    if all(required):
        result["status"] = "equilibrated"
        result["recommendation"] = "write_data_and_continue_next_rh"
        result["reasons"].append("All equilibrium criteria passed in the final window.")
    elif require_previous_window_slopes and not result["checks"].get("previous_window_water_slopes_ok", True):
        result["status"] = "marginal"
        result["recommendation"] = "continue_current_rh"
    else:
        result["status"] = "not_equilibrated"
        result["recommendation"] = "continue_current_rh"

    return result


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("monitor", type=Path, nargs="+", help="One or more monitor files in chronological order.")
    p.add_argument("--window-steps", type=float, default=500000.0,
                   help="Use the last this many MD steps for equilibrium judgment. Default: 500000.")
    p.add_argument("--last-fraction", type=float, default=0.3,
                   help="Used only if --window-steps <= 0.")
    p.add_argument("--auto-offset-restarts", action="store_true",
                   help="If timestep restarts from zero/nonmonotonic between files, offset later segments.")
    p.add_argument("--min-points", type=int, default=50)
    p.add_argument("--json", type=Path, default=Path("equilibrium_status.json"))

    p.add_argument("--total-cv-max", type=float, default=0.03)
    p.add_argument("--inter-cv-max", type=float, default=0.05)
    p.add_argument("--ext-cv-max", type=float, default=0.08)
    p.add_argument("--total-slope-frac", type=float, default=0.01)
    p.add_argument("--inter-slope-frac", type=float, default=0.02)
    p.add_argument("--ext-slope-frac", type=float, default=0.02)
    p.add_argument("--min-water-slope-abs", type=float, default=1.0)
    p.add_argument("--basal-slope-max", type=float, default=0.05)
    p.add_argument("--sum-tol", type=float, default=0.5)
    p.add_argument("--require-previous-window-slopes", action="store_true")
    args = p.parse_args()

    data = read_monitors(args.monitor, auto_offset_restarts=args.auto_offset_restarts)
    result = analyze(
        data=data,
        window_steps=args.window_steps,
        last_fraction=args.last_fraction,
        min_points=args.min_points,
        total_cv_max=args.total_cv_max,
        inter_cv_max=args.inter_cv_max,
        ext_cv_max=args.ext_cv_max,
        total_slope_frac_per_100k=args.total_slope_frac,
        inter_slope_frac_per_100k=args.inter_slope_frac,
        ext_slope_frac_per_100k=args.ext_slope_frac,
        min_water_slope_abs=args.min_water_slope_abs,
        basal_slope_abs_per_100k=args.basal_slope_max,
        sum_tol=args.sum_tol,
        require_previous_window_slopes=args.require_previous_window_slopes,
    )

    args.json.write_text(json.dumps(result, indent=2))
    print(json.dumps({
        "status": result["status"],
        "recommendation": result["recommendation"],
        "step_end": result["step_end"],
        "window": [result["window_step_start"], result["window_step_end"]],
        "reasons": result["reasons"],
    }, indent=2))


if __name__ == "__main__":
    main()
